source 'http://rubygems.org'

gem 'rails', '3.0.6'
gem 'unicorn'
gem 'pg'

gem 'acts-as-taggable-on'
gem 'capistrano'
gem 'haml'
gem 'sass'
gem 'compass'
gem 'formtastic'
gem 'heroku'
gem 'hirb'
gem 'inherited_resources'
gem 'rake', '0.9.2'
gem 'simple_form'
gem 'state_machine'
gem 'RedCloth'

group :development, :test do
  gem 'autotest'
  gem 'autotest-growl'
  gem 'autotest-fsevent'
  gem 'capybara', :git => 'https://github.com/jnicklas/capybara.git', :tag => '1.0.0.beta1'
  gem 'database_cleaner'
  gem 'faker'
  gem 'itslog'
  gem 'launchy' # for save_and_open_page
  gem "machinist", '>= 2.0.0.beta2'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'spork'
  gem 'steak'
  gem 'fuubar'
  gem 'timecop'
end
